language: python
python: 3.4.3

install: 
  - pip install -U 'pip<8.1.2' setuptools wheel codecov
  - pip install -r requirements.txt

script: nosetests

after_success: codecov  
  
notifications:
  email: true
  
