language: python
python: 3.4.3

install: 
  - pip install -U 'pip<8.1.2' setuptools wheel codecov
  - pip install -r requirements.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: nosetests --with-coverage

after_success: 
  - bash <(curl -s https://codecov.io/bash)  
  
notifications:
  email: true
  
